DROP TABLE IF EXISTS voters CASCADE;
DROP TABLE IF EXISTS polls CASCADE;
DROP TABLE IF EXISTS choices CASCADE;
DROP TABLE IF EXISTS votes CASCADE;

CREATE TABLE polls (
  id SERIAL PRIMARY KEY NOT NULL,
  creator_name VARCHAR(255) NOT NULL,
  creator_email VARCHAR(255) NOT NULL,
  admin_url VARCHAR(255),
  submission_url VARCHAR(255),
  question VARCHAR(255)
);

CREATE TABLE voters (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  poll_id INTEGER NOT NULL REFERENCES polls(id)
);

CREATE TABLE choices (
  id SERIAL PRIMARY KEY NOT NULL,
  poll_id INTEGER REFERENCES polls(id),
  description TEXT,
  title VARCHAR(255)
);

CREATE TABLE voter_choices (
  id SERIAL PRIMARY KEY NOT NULL,
  voter_id INTEGER NOT NULL REFERENCES voters(id),
  choice_id INTEGER NOT NULL REFERENCES choices(id),
  choice_rank INTEGER
);
